// Package init provides the init command handler for generating AURA.md.
package init

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/oneliang/aura/shared/pkg/config"
)

// Handler handles the init command for generating AURA.md.
// Note: This handler is deprecated. Use SDK directly (see cli/pkg/commands/init.go).
type Handler struct {
	Config       *config.Config
	ConfigLoader ConfigLoader
}

// ConfigLoader interface for loading configuration.
type ConfigLoader interface {
	Load() (*config.Config, error)
}

// GetCommands returns the available init commands.
func (h *Handler) GetCommands() []CommandInfo {
	return []CommandInfo{
		{
			Name:        "command_init",
			DisplayName: "Init",
			Description: "Initialize AURA.md with workspace documentation",
			Params: []ParamInfo{
				{
					Name:     "force",
					Type:     "bool",
					Required: false,
					Desc:     "Force regeneration even if AURA.md exists",
				},
			},
		},
	}
}

// Execute executes the init command.
// Note: This method is deprecated and returns a simple message.
// For LLM-powered init, use TUI `/init` or CLI `aura init`.
func (h *Handler) Execute(ctx context.Context, cmd string, params map[string]any) (string, error) {
	cwd, ok := params["cwd"].(string)
	if !ok || cwd == "" {
		cwd, _ = os.Getwd()
	}

	force := params["force"] == true
	claudeMdPath := filepath.Join(cwd, "AURA.md")

	if !force {
		if _, err := os.Stat(claudeMdPath); err == nil {
			return fmt.Sprintf("AURA.md already exists at: %s\nUse force=true to regenerate.", claudeMdPath), nil
		}
	}

	// Write basic template
	content := "# AURA.md\n\n" +
		"This file provides guidance for Aura when working in this workspace.\n\n" +
		"**Note**: For richer documentation adapted to your workspace type, use:\n" +
		"- TUI: /init command\n" +
		"- CLI: aura init command\n\n" +
		"## Workspace Overview\n\n" +
		"Describe the purpose and structure of this workspace.\n\n" +
		"---\n\n" +
		"*Generated by aura init*\n"

	if err := os.WriteFile(claudeMdPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write AURA.md: %w", err)
	}

	return fmt.Sprintf("Generated basic AURA.md at: %s\nFor richer content, use TUI /init or CLI aura init.", claudeMdPath), nil
}